include $(GNUSTEP_MAKEFILES)/common.make

FRAMEWORK_NAME=SimpleWebKit

SimpleWebKit_HEADER_FILES = \
DOM.h \
DOMCore.h \
DOMCSS.h \
DOMHTML.h \
DOMRange.h \
ECMAScriptEvaluator.h \
ECMAScriptParser.h \
ECMAScriptPrototypes.h \
Private.h \
WebArchive.h \
WebBackForwardList.h \
WebCSSDocumentRepresentation.h \
WebDocumentRepresentation.h \
WebDOMOperations.h \
WebDataSource.h \
WebDocument.h \
WebDownload.h \
WebFrame.h \
WebFrameLoadDelegate.h \
WebFrameView.h \
WebHTMLDocumentView.h \
WebHTMLDocumentRepresentation.h \
WebHistory.h \
WebHistoryItem.h \
WebImageDocumentRepresentation.h \
WebKit.h \
WebPDFDocumentRepresentation.h \
WebPlugin.h \
WebResource.h \
WebResourceLoadDelegate.h \
WebScriptObject.h \
WebUIDelegate.h \
WebUndefined.h \
WebView.h \
WebXMLDocumentRepresentation.h 

SimpleWebKit_HEADER_FILES_INSTALL_DIR = WebKit

SimpleWebKit_OBJC_FILES = \
DOMCore.m \
DOMCSS.m \
DOMHTML.m \
DOMRange.m \
ECMAScriptEvaluator.m \
ECMAScriptParser.m \
ECMAScriptPrototypes.m \
WebArchive.m \
WebBackForwardList.m \
WebCSSDocumentRepresentation.m \
WebDocumentRepresentation.m \
WebDOMOperations.m \
WebDataSource.m \
WebFrame.m \
WebFrameView.m \
WebHTMLDocumentView.m \
WebHTMLDocumentRepresentation.m \
WebHistory.m \
WebHistoryItem.m \
WebImageDocumentRepresentation.m \
WebPDFDocumentRepresentation.m \
WebResource.m \
WebScriptObject.m \
WebView.m \
WebXMLDocumentRepresentation.m

include $(GNUSTEP_MAKEFILES)/framework.make

