include $(GNUSTEP_MAKEFILES)/common.make

FRAMEWORK_NAME=SimpleWebKit

SimpleWebKit_HEADER_FILES = \
NSXMLParser.h \
DOM.h \
DOMCore.h \
DOMHTML.h \
Private.h \
WebBackForwardList.h \
WebDOMOperations.h \
WebDataSource.h \
WebDocument.h \
WebFrame.h \
WebFrameLoadDelegate.h \
WebFrameView.h \
WebHTMLDocumentView.h \
WebHTMLDocumentRepresentation.h \
WebHistory.h \
WebHistoryItem.h \
WebImageDocumentRepresentation.h \
WebKit.h \
WebPDFDocumentRepresentation.h \
WebPlugin.h \
WebResource.h \
WebScriptObject.h \
WebUIDelegate.h \
WebView.h \
WebXMLDocumentRepresentation.h 

SimpleWebKit_HEADER_FILES_INSTALL_DIR = WebKit

SimpleWebKit_OBJC_FILES = \
NSXMLParser.m \
DOMCore.m \
DOMHTML.m \
WebBackForwardList.m \
WebDOMOperations.m \
WebDataSource.m \
WebFrame.m \
WebFrameView.m \
WebHTMLDocumentView.m \
WebHTMLDocumentRepresentation.m \
WebHistory.m \
WebHistoryItem.m \
WebImageDocumentRepresentation.m \
WebPDFDocumentRepresentation.m \
WebResource.m \
WebScriptObject.m \
WebView.m \
WebXMLDocumentRepresentation.m

include $(GNUSTEP_MAKEFILES)/framework.make

